services:
  - type: web
    name: game-showcase-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn game_showcase.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.9"
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: USE_S3_MEDIA
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_ENDPOINT_URL
        sync: false
      - key: AWS_S3_CUSTOM_DOMAIN
        sync: false
