# Generated by Django 5.2.13 on 2026-04-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='build_archive',
            field=models.FileField(blank=True, null=True, upload_to='project_archives/', verbose_name='ZIP архив билда'),
        ),
        migrations.AlterField(
            model_name='project',
            name='build_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на билд'),
        ),
    ]
