# Generated by Django 5.2.13 on 2026-05-24 11:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_project_build_archive_alter_project_build_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Оценка от 0 до 100 баллов', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка'),
        ),
        migrations.AddField(
            model_name='project',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название команды'),
        ),
        migrations.CreateModel(
            name='ProjectArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('git', 'Git'), ('figma', 'Figma'), ('drive', 'Google Drive'), ('other', 'Другое')], max_length=30, verbose_name='Тип артефакта')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='games.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Артефакт',
                'verbose_name_plural': 'Артефакты',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('role', models.CharField(max_length=150, verbose_name='Роль в команде')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='games.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Состав команды',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
