# Generated by Django 5.2.13 on 2026-05-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_project_score_project_team_name_projectartifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий / вопрос'),
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='application',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрена')], default='pending', max_length=30, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='application',
            name='role',
            field=models.CharField(choices=[('expert', 'Эксперт'), ('curator', 'Куратор')], default='expert', max_length=30, verbose_name='Роль'),
        ),
    ]
