# Generated by Django 5.2.13 on 2026-05-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_application_comment_application_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Загрузите картинку с компьютера (рекомендуется для обложки карточки).', null=True, upload_to='project_images/', verbose_name='Файл изображения'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_url',
            field=models.URLField(blank=True, help_text='Альтернатива загрузке: публичная ссылка https://... (не путь вида C:\\Users\\...).', verbose_name='Ссылка на файл'),
        ),
    ]
